{
 "title": "数据展示界面",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "拓扑信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "拓扑信息",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1s),\n  linkid AS metric,\n  value\nFROM link_info\nWHERE\n  $__timeFilter(time)\nORDER BY $__timeGroup(time,1s)"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  switchid AS metric,\n  averagebytes\nFROM switch_info\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  switchid AS metric,\n  averagepkts\nFROM switch_info\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  switchid AS metric,\n  maxbytes\nFROM switch_info\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  switchid AS metric,\n  maxpkts\nFROM switch_info\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  switchid AS metric,\n  totalbytes\nFROM switch_info\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  switchid AS metric,\n  totalflownums\nFROM switch_info\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  switchid AS metric,\n  totalflowrate\nFROM switch_info\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  linkid AS metric,\n  flag\nFROM highlight_link\nORDER BY time"
    }
   ]
  },
  {
   "title": "用户路由信息表",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  mac AS metric,\n  path,\n  cost_time,\n  safe_route\nFROM highlight_route"
    }
   ]
  },
  {
   "title": "交换机信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "交换机信息",
     "type": "table",
     "gridPos": { "h": 25, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  switchid,\n  averagebytes,\n  averagepkts,\n  maxbytes,\n  maxpkts,\n  totalbytes,\n  totalflownums,\n  totalflowrate\nFROM switch_info"
      }
     ]
    }
   ]
  },
  { "title": "上下行链路信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "上行链路",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  mac,\n  ip,\n  average_flow_rate,\n  maxflow,\n  protocol,\n  dst_port,\n  life,\n  visit_cnt\nFROM flow_info\nWHERE\n  flag = 0"
    }
   ]
  },
  {
   "title": "下行链路",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  ip,\n  mac,\n  average_flow_rate,\n  maxflow,\n  protocol,\n  src_port,\n  life,\n  visit_cnt\nFROM flow_info\nWHERE\n  flag = 1"
    }
   ]
  },
  { "title": "用户信任度动态评估", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "用户信任度值",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 13, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  id AS metric,\n  value\nFROM confidence\nORDER BY time"
    }
   ]
  },
  {
   "title": "用户信任度表",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\n  id,\n  mac,\n  ip\nFROM confidence"
    }
   ]
  },
  {
   "title": "用户信任度过低信息提示",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT\n  temptime AS \"断连时间\",\n  message AS \"提示信息\"\nFROM msg_queue"
    }
   ]
  }
 ]
}