spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/mybatis?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: uEstC318.#

# knife4j-redis-lettuce配置
knife4j:
  redis:
    # 序列化方式
    jsonSerialType: Fastjson
    # redis ip
    host: 192.168.1.49    
    password:
    # redis port
    port: 6379    
    # redis databases
    databases: [ 0,2,7,9 ]
    timeout: 60s
    lettuce:
      pool:
        max-active: 50
        max-wait: -1ms
        max-idle: 8
        min-idle: 0